import type { ActivityTemplate } from "$lib/domain/templates";
import { BLUE, DARK_GREEN, GRAY, GREEN, ORANGE, PINK, RED, TEAL, VIOLET, YELLOW, l, node, word } from "./words";

export const BUSINESS_TEMPLATES: ActivityTemplate[] = [
  {
    id: "manager",
    category: "business",
    name: l(
      "Manager or team lead",
      "ผู้จัดการ / หัวหน้าทีม",
      "经理 / 团队负责人",
      "マネージャー／チームリーダー",
      "매니저 / 팀 리더",
    ),
    description: l(
      "Time for your people, your plans and your own growth, not just meetings.",
      "เวลาให้ทีมของคุณ แผนงาน และการเติบโตของตัวเอง ไม่ใช่แค่ประชุม",
      "留给团队、计划和自身成长的时间，而不只是开会。",
      "会議だけでなく、メンバー、計画、自分の成長にも時間を使います。",
      "회의만이 아니라 팀원, 계획, 나 자신의 성장에 시간을 써요.",
    ),
    nodes: [
      node(l("People", "ทีมงาน", "团队成员", "メンバー", "팀원"), ORANGE, [
        node(l("One-on-ones", "คุยตัวต่อตัว", "一对一沟通", "1on1", "1:1 면담")),
        node(l("Team meetings", "ประชุมทีม", "团队会议", "チーム会議", "팀 회의")),
        node(l("Hiring", "สรรหาบุคลากร", "招聘", "採用", "채용")),
      ]),
      node(word.strategy, BLUE, [
        node(word.planning),
        node(l("Reviews and reports", "รีวิวและรายงาน", "复盘与汇报", "レビューと報告", "리뷰와 보고")),
      ]),
      node(l("Execution", "การลงมือ", "执行", "実行", "실행"), RED, [node(word.followUps), node(word.email)]),
      node(l("Growth", "การเติบโต", "成长", "成長", "성장"), VIOLET, [
        node(word.reading),
        node(l("Networking", "สร้างเครือข่าย", "人脉拓展", "ネットワーキング", "네트워킹")),
      ]),
    ],
  },
  {
    id: "project-manager",
    category: "business",
    name: l("Project manager", "ผู้จัดการโครงการ", "项目经理", "プロジェクトマネージャー", "프로젝트 매니저"),
    description: l(
      "Plan the work, coordinate people and keep risks and reporting under control.",
      "วางแผนงาน ประสานงานผู้คน และควบคุมความเสี่ยงและการรายงาน",
      "规划工作、协调人员，并管控风险与汇报。",
      "作業を計画し、人を調整し、リスクと報告を管理します。",
      "업무를 계획하고 사람들을 조율하며 위험과 보고를 관리해요.",
    ),
    nodes: [
      node(word.planning, BLUE, [
        node(l("Scope and schedule", "ขอบเขตและตารางเวลา", "范围与进度", "スコープとスケジュール", "범위와 일정")),
        node(l("Budget", "งบประมาณ", "预算", "予算", "예산")),
      ]),
      node(l("Coordinating the team", "ประสานงานทีม", "协调团队", "チームの調整", "팀 조율"), ORANGE, [
        node(word.meetings),
        node(word.followUps),
      ]),
      node(word.stakeholders, PINK),
      node(l("Risks and issues", "ความเสี่ยงและปัญหา", "风险与问题", "リスクと課題", "위험과 이슈"), RED),
      node(word.reporting, VIOLET),
      node(word.learning, DARK_GREEN),
    ],
  },
  {
    id: "sales",
    category: "business",
    name: l("Sales", "การขาย", "销售", "営業", "영업"),
    description: l(
      "Prospect, talk, propose and follow up, with time to keep your records straight.",
      "หาลูกค้า พูดคุย เสนอ และติดตามผล พร้อมเวลาจัดบันทึกให้เรียบร้อย",
      "开拓客户、沟通、提案和跟进，也留时间整理记录。",
      "見込み客の開拓、商談、提案、フォローアップ。記録を整える時間も。",
      "잠재 고객 발굴, 상담, 제안, 후속 연락. 기록 정리 시간도.",
    ),
    nodes: [
      node(l("Prospecting", "หาลูกค้าใหม่", "开拓客户", "見込み客の開拓", "잠재 고객 발굴"), BLUE),
      node(l("Calls and meetings", "โทรและประชุม", "电话与会议", "電話と商談", "통화와 미팅"), ORANGE),
      node(l("Proposals and quotes", "ข้อเสนอและใบเสนอราคา", "提案与报价", "提案と見積もり", "제안과 견적"), VIOLET),
      node(word.followUps, YELLOW),
      node(l("CRM and records", "CRM และบันทึก", "CRM 与记录", "CRM と記録", "CRM과 기록"), GRAY),
      node(word.learning, DARK_GREEN),
    ],
  },
  {
    id: "marketer",
    category: "business",
    name: l("Marketer", "นักการตลาด", "营销人员", "マーケター", "마케터"),
    description: l(
      "Strategy, content, campaigns and results, kept in a steady cycle.",
      "กลยุทธ์ เนื้อหา แคมเปญ และผลลัพธ์ ในวงจรที่สม่ำเสมอ",
      "策略、内容、活动与成效，保持稳定的循环。",
      "戦略、コンテンツ、キャンペーン、成果を安定したサイクルで。",
      "전략, 콘텐츠, 캠페인, 성과를 꾸준한 사이클로.",
    ),
    nodes: [
      node(word.strategy, BLUE),
      node(l("Content creation", "สร้างเนื้อหา", "内容创作", "コンテンツ制作", "콘텐츠 제작"), PINK, [
        node(word.writing),
        node(l("Design and visuals", "ออกแบบและภาพ", "设计与视觉", "デザインとビジュアル", "디자인과 비주얼")),
      ]),
      node(l("Campaigns", "แคมเปญ", "营销活动", "キャンペーン", "캠페인"), ORANGE),
      node(word.socialMedia, VIOLET),
      node(l("Analytics and reporting", "วิเคราะห์และรายงาน", "分析与汇报", "分析と報告", "분석과 보고"), YELLOW),
      node(word.meetings, GRAY),
    ],
  },
  {
    id: "founder",
    category: "business",
    name: l(
      "Founder or entrepreneur",
      "ผู้ก่อตั้ง / ผู้ประกอบการ",
      "创始人 / 创业者",
      "創業者／起業家",
      "창업가",
    ),
    description: l(
      "Product, customers, money and people: wear each hat on purpose.",
      "ผลิตภัณฑ์ ลูกค้า เงิน และคน: สวมหมวกแต่ละใบอย่างตั้งใจ",
      "产品、客户、资金和团队：有意识地切换每个角色。",
      "製品、顧客、お金、人。それぞれの役割を意識して切り替えます。",
      "제품, 고객, 돈, 사람. 각 역할을 의도적으로 맡아요.",
    ),
    nodes: [
      node(l("Product", "ผลิตภัณฑ์", "产品", "プロダクト", "제품"), VIOLET),
      node(l("Customers and sales", "ลูกค้าและการขาย", "客户与销售", "顧客と営業", "고객과 영업"), ORANGE),
      node(l("Operations", "การดำเนินงาน", "运营", "オペレーション", "운영"), BLUE),
      node(l("Finance and fundraising", "การเงินและระดมทุน", "财务与融资", "財務と資金調達", "재무와 투자 유치"), YELLOW),
      node(l("Team and hiring", "ทีมและการสรรหา", "团队与招聘", "チームと採用", "팀과 채용"), PINK),
      node(word.learning, DARK_GREEN),
      node(word.health, GREEN),
    ],
  },
  {
    id: "customer-support",
    category: "business",
    name: l("Customer support", "ฝ่ายสนับสนุนลูกค้า", "客户支持", "カスタマーサポート", "고객 지원"),
    description: l(
      "Answer chats, calls and tickets, and improve the answers for next time.",
      "ตอบแชท โทรศัพท์ และทิกเก็ต และปรับปรุงคำตอบสำหรับครั้งต่อไป",
      "回复聊天、电话和工单，并改进下次的答案。",
      "チャット、電話、チケットに対応し、次のために回答を改善します。",
      "채팅, 전화, 티켓에 답하고 다음을 위해 답변을 개선해요.",
    ),
    nodes: [
      node(l("Chats and email", "แชทและอีเมล", "在线聊天与邮件", "チャットとメール", "채팅과 이메일"), BLUE),
      node(l("Phone calls", "โทรศัพท์", "电话沟通", "電話対応", "전화 응대"), ORANGE),
      node(word.tickets, RED),
      node(l("Knowledge base", "ฐานความรู้", "知识库", "ナレッジベース", "지식 베이스"), VIOLET),
      node(l("Team sync", "ซิงก์ทีม", "团队同步", "チーム連携", "팀 공유"), YELLOW),
      node(word.training, GRAY),
      node(word.breaks, GREEN),
    ],
  },
  {
    id: "accountant",
    category: "business",
    name: l("Accountant or finance", "นักบัญชี / การเงิน", "会计 / 财务", "会計・財務", "회계 / 재무"),
    description: l(
      "Bookkeeping, reports and compliance on a calendar, with time for clients.",
      "การทำบัญชี รายงาน และการปฏิบัติตามกฎ ตามปฏิทิน พร้อมเวลาสำหรับลูกค้า",
      "按日历完成记账、报表与合规，也留时间给客户。",
      "記帳、レポート、コンプライアンスをカレンダー通りに。顧客の時間も。",
      "장부, 보고서, 규정 준수를 일정대로, 고객 시간도.",
    ),
    nodes: [
      node(l("Bookkeeping", "ทำบัญชี", "记账", "記帳", "장부 작성"), BLUE),
      node(l("Financial reporting", "รายงานการเงิน", "财务报告", "財務報告", "재무 보고"), VIOLET),
      node(l("Tax and compliance", "ภาษีและการปฏิบัติตามกฎ", "税务与合规", "税務とコンプライアンス", "세무와 규정 준수"), RED),
      node(word.clientMeetings, ORANGE),
      node(l("Analysis and forecasts", "วิเคราะห์และคาดการณ์", "分析与预测", "分析と予測", "분석과 예측"), YELLOW),
      node(word.admin, GRAY),
    ],
  },
  {
    id: "hr",
    category: "business",
    name: l("HR or people team", "ฝ่ายบุคคล", "人力资源", "人事", "인사팀"),
    description: l(
      "Hiring, onboarding, supporting employees and keeping policies fair.",
      "สรรหา ปฐมนิเทศ สนับสนุนพนักงาน และดูแลนโยบายให้เป็นธรรม",
      "招聘、入职、员工支持，并保持制度公平。",
      "採用、オンボーディング、従業員サポート、公平な制度づくり。",
      "채용, 온보딩, 직원 지원, 공정한 제도 운영.",
    ),
    nodes: [
      node(l("Recruiting", "สรรหาบุคลากร", "招聘", "採用", "채용"), BLUE, [
        node(l("Screening", "คัดกรอง", "筛选简历", "書類選考", "서류 검토")),
        node(l("Interviews", "สัมภาษณ์", "面试", "面接", "면접")),
      ]),
      node(l("Onboarding", "ปฐมนิเทศ", "新员工入职", "オンボーディング", "온보딩"), GREEN),
      node(l("Employee support", "สนับสนุนพนักงาน", "员工支持", "従業員サポート", "직원 지원"), PINK),
      node(l("Policies and compliance", "นโยบายและการปฏิบัติตามกฎ", "制度与合规", "制度とコンプライアンス", "제도와 규정 준수"), VIOLET),
      node(word.training, ORANGE),
      node(word.admin, GRAY),
    ],
  },
  {
    id: "consultant",
    category: "business",
    name: l("Consultant", "ที่ปรึกษา", "顾问", "コンサルタント", "컨설턴트"),
    description: l(
      "Client work, analysis and presentations, with time to find the next client.",
      "งานลูกค้า การวิเคราะห์ และการนำเสนอ พร้อมเวลาหาลูกค้ารายต่อไป",
      "客户项目、分析与演示，同时留时间开拓下一个客户。",
      "クライアントワーク、分析、プレゼンに、次の顧客を探す時間も。",
      "고객 업무, 분석, 발표에 다음 고객을 찾을 시간까지.",
    ),
    nodes: [
      node(l("Client work", "งานลูกค้า", "客户项目", "クライアントワーク", "고객 업무"), BLUE),
      node(word.analysis, VIOLET),
      node(l("Presentations and reports", "การนำเสนอและรายงาน", "演示与报告", "プレゼンと報告書", "발표와 보고서"), ORANGE),
      node(l("Finding new clients", "หาลูกค้าใหม่", "开拓新客户", "新規顧客の開拓", "신규 고객 개척"), YELLOW),
      node(word.travel, TEAL),
      node(word.learning, DARK_GREEN),
    ],
  },
  {
    id: "remote-worker",
    category: "business",
    name: l("Remote worker", "คนทำงานทางไกล", "远程办公者", "リモートワーカー", "원격 근무자"),
    description: l(
      "Focus time, meetings and chat, with a clear start, a clear end and real breaks.",
      "เวลาโฟกัส ประชุม และแชท พร้อมการเริ่มและเลิกงานที่ชัดเจน และพักจริง ๆ",
      "专注时间、会议与沟通，上下班界限清晰，休息到位。",
      "集中時間、会議、チャット。始まりと終わりを明確に、休憩もしっかり。",
      "집중 시간, 회의, 채팅. 시작과 끝을 분명히 하고 제대로 쉬어요.",
    ),
    nodes: [
      node(word.deepWork, VIOLET),
      node(word.meetings, ORANGE),
      node(l("Messages and async", "ข้อความและงานไม่พร้อมกัน", "消息与异步沟通", "メッセージと非同期連絡", "메시지와 비동기 소통"), BLUE),
      node(l("Start and end of day", "เริ่มและเลิกงาน", "上下班切换", "始業と終業", "업무 시작과 마무리"), GRAY, [
        node(l("Plan the day", "วางแผนวันนี้", "规划今天", "今日の計画", "오늘 계획")),
        node(word.shutdown),
      ]),
      node(word.breaks, GREEN),
      node(l("Movement and fresh air", "ขยับตัวและรับอากาศ", "活动与新鲜空气", "運動と外の空気", "움직임과 바깥 공기"), RED),
      node(l("Staying connected", "ติดต่อกับผู้คน", "保持联系", "人とのつながり", "연결 유지"), PINK),
    ],
  },
];
