import type { ActivityTemplate } from "$lib/domain/templates";
import { BLUE, GRAY, GREEN, ORANGE, PINK, RED, TEAL, VIOLET, YELLOW, l, node, word } from "./words";

export const TECHNIQUE_TEMPLATES: ActivityTemplate[] = [
  {
    id: "eisenhower",
    category: "technique",
    name: l(
      "Eisenhower matrix (4Q)",
      "เมทริกซ์ไอเซนฮาวร์ (4Q)",
      "艾森豪威尔矩阵（四象限）",
      "アイゼンハワー・マトリクス（4象限）",
      "아이젠하워 매트릭스 (4사분면)",
    ),
    description: l(
      "Sort your time by urgent and important: do first, schedule, delegate, don't do.",
      "จัดเวลาตามความเร่งด่วนและความสำคัญ: ทำก่อน วางตาราง มอบหมาย ไม่ทำ",
      "按紧急和重要程度分配时间：马上做、计划做、委派、不做。",
      "緊急度と重要度で時間を分けます。最優先、予定する、任せる、やらない。",
      "긴급함과 중요도로 시간을 나눠요. 먼저 하기, 일정 잡기, 맡기기, 하지 않기.",
    ),
    nodes: [
      node(l("Do first", "ทำก่อน", "马上做", "最優先", "먼저 하기"), RED, [
        node(l("Urgent work", "งานด่วน", "紧急工作", "急ぎの仕事", "급한 일")),
        node(l("Deadlines", "กำหนดส่ง", "截止事项", "締め切り", "마감")),
      ]),
      node(l("Schedule", "วางตาราง", "计划做", "予定する", "일정 잡기"), GREEN, [
        node(word.planning),
        node(word.deepWork),
        node(word.exercise),
        node(word.learning),
      ]),
      node(l("Delegate", "มอบหมาย", "委派", "任せる", "맡기기"), ORANGE, [
        node(l("Routine tasks", "งานประจำ", "例行事务", "ルーティン作業", "반복 업무")),
        node(l("Hand over to others", "มอบให้ผู้อื่น", "交给他人", "人に任せる", "다른 사람에게 맡기기")),
      ]),
      node(l("Don't do", "ไม่ทำ", "不做", "やらない", "하지 않기"), BLUE, [
        node(word.socialMedia),
        node(l("Random videos", "ดูคลิปเรื่อยเปื่อย", "随便刷视频", "ダラダラ動画", "무심코 보는 영상")),
      ]),
    ],
  },
  {
    id: "pomodoro",
    category: "technique",
    name: l("Pomodoro technique", "เทคนิคโพโมโดโร", "番茄工作法", "ポモドーロ・テクニック", "포모도로 기법"),
    description: l(
      "Work in focused rounds with short breaks. One 25-minute round is about three blocks.",
      "ทำงานเป็นรอบโฟกัสสลับพักสั้น ๆ หนึ่งรอบ 25 นาทีประมาณสามบล็อก",
      "专注工作一轮后短暂休息。一个 25 分钟的番茄钟约占三个时间块。",
      "集中して働き、短く休みます。25 分の 1 ラウンドは約 3 ブロックです。",
      "집중해서 일하고 짧게 쉬어요. 25분 한 번은 약 3블록이에요.",
    ),
    nodes: [
      node(l("Focus round", "รอบโฟกัส", "专注时段", "集中ラウンド", "집중 라운드"), RED),
      node(l("Short break", "พักสั้น", "短休息", "短い休憩", "짧은 휴식"), GREEN),
      node(l("Long break", "พักยาว", "长休息", "長い休憩", "긴 휴식"), BLUE),
      node(word.review, VIOLET),
    ],
  },
  {
    id: "deep-work",
    category: "technique",
    name: l(
      "Deep work and shallow work",
      "งานเชิงลึกและงานผิวเผิน",
      "深度工作与浅层工作",
      "ディープワークとシャローワーク",
      "딥 워크와 섈로 워크",
    ),
    description: l(
      "Protect long stretches for demanding work, and batch the small stuff.",
      "ปกป้องช่วงเวลายาวสำหรับงานที่ต้องใช้สมาธิ และรวมงานจิปาถะไว้ด้วยกัน",
      "为高难度工作保留整块时间，把琐事集中处理。",
      "負荷の高い仕事のために長い時間を確保し、細かい作業はまとめます。",
      "집중이 필요한 일에 긴 시간을 확보하고 잡무는 모아서 처리해요.",
    ),
    nodes: [
      node(word.deepWork, VIOLET, [
        node(l("Main project", "โปรเจกต์หลัก", "主要项目", "メインプロジェクト", "핵심 프로젝트")),
        node(l("Thinking and design", "คิดและออกแบบ", "思考与设计", "思考と設計", "생각과 설계")),
      ]),
      node(l("Shallow work", "งานผิวเผิน", "浅层工作", "シャローワーク", "섈로 워크"), ORANGE, [
        node(word.email),
        node(l("Messages", "ข้อความแชท", "消息", "メッセージ", "메시지")),
        node(word.admin),
      ]),
      node(word.buffer, GRAY),
      node(word.breaks, GREEN),
      node(word.shutdown, TEAL),
    ],
  },
  {
    id: "gtd",
    category: "technique",
    name: l(
      "Getting Things Done (GTD)",
      "Getting Things Done (GTD)",
      "GTD 工作法",
      "GTD（Getting Things Done）",
      "GTD (Getting Things Done)",
    ),
    description: l(
      "Capture everything, decide what it means, then do the next action.",
      "จดทุกอย่าง ตัดสินใจว่าคืออะไร แล้วลงมือทำขั้นต่อไป",
      "把所有事情记下来，想清楚含义，然后做下一步行动。",
      "すべて書き出し、意味を決め、次の行動を実行します。",
      "모든 것을 적고, 의미를 정하고, 다음 행동을 실행해요.",
    ),
    nodes: [
      node(l("Capture", "จดบันทึก", "收集", "収集", "수집"), YELLOW),
      node(l("Clarify and organize", "จัดระเบียบ", "理清与整理", "明確化と整理", "정리하기"), BLUE),
      node(l("Do", "ลงมือทำ", "执行", "実行", "실행"), RED, [
        node(l("Next actions", "งานถัดไป", "下一步行动", "次の行動", "다음 행동")),
        node(word.projects),
        node(l("Waiting for", "รอผู้อื่น", "等待他人", "待ち", "기다리는 중")),
      ]),
      node(word.review, GREEN, [
        node(l("Daily check", "เช็กประจำวัน", "每日检查", "毎日チェック", "일일 점검")),
        node(l("Weekly review", "ทบทวนประจำสัปดาห์", "每周回顾", "週次レビュー", "주간 리뷰")),
      ]),
    ],
  },
  {
    id: "time-blocking",
    category: "technique",
    name: l(
      "Time blocking day",
      "วันแบบบล็อกเวลา",
      "时间块工作日",
      "タイムブロッキングの一日",
      "타임 블로킹 하루",
    ),
    description: l(
      "Give every hour a job: focus blocks, admin, meetings and buffers.",
      "ให้ทุกชั่วโมงมีหน้าที่: บล็อกโฟกัส งานธุรการ การประชุม และเวลาสำรอง",
      "给每个小时分配任务：专注块、事务块、会议和缓冲。",
      "1 時間ごとに役割を決めます。集中、事務、会議、バッファ。",
      "모든 시간에 역할을 줘요. 집중 블록, 행정, 회의, 여유 시간.",
    ),
    nodes: [
      node(l("Focus blocks", "บล็อกโฟกัส", "专注块", "集中ブロック", "집중 블록"), VIOLET, [
        node(l("Priority project", "งานสำคัญที่สุด", "首要项目", "最優先プロジェクト", "최우선 프로젝트")),
        node(l("Second project", "งานรอง", "次要项目", "二番目のプロジェクト", "두 번째 프로젝트")),
      ]),
      node(word.admin, GRAY),
      node(word.meetings, ORANGE),
      node(word.buffer, YELLOW),
      node(word.breaks, GREEN),
      node(word.personalTime, TEAL),
    ],
  },
  {
    id: "eat-the-frog",
    category: "technique",
    name: l("Eat the frog", "กินกบก่อน", "先吃青蛙", "最初にカエルを食べる", "개구리부터 먹기"),
    description: l(
      "Do the hardest task first, while your energy is highest.",
      "ทำงานที่ยากที่สุดก่อน ตอนที่พลังงานสูงสุด",
      "趁精力最旺盛，先做最难的任务。",
      "エネルギーが高いうちに、いちばん難しい仕事から。",
      "에너지가 가장 높을 때 가장 어려운 일부터 해요.",
    ),
    nodes: [
      node(
        l("The frog (hardest task)", "กบตัวใหญ่ (งานที่ยากที่สุด)", "青蛙（最难的任务）", "カエル（最難関の仕事）", "개구리 (가장 어려운 일)"),
        GREEN,
      ),
      node(l("Important tasks", "งานสำคัญ", "重要任务", "重要な仕事", "중요한 일"), BLUE),
      node(l("Quick wins", "งานเสร็จไว", "速赢任务", "すぐ終わる仕事", "빠른 성과"), YELLOW),
      node(word.breaks, TEAL),
      node(word.review, VIOLET),
    ],
  },
  {
    id: "ivy-lee",
    category: "technique",
    name: l("Ivy Lee method", "วิธีไอวี ลี", "艾维·李法", "アイビー・リー・メソッド", "아이비 리 방법"),
    description: l(
      "Each evening pick your six most important tasks and do them in order tomorrow.",
      "ทุกเย็นเลือกงานสำคัญหกอย่างและทำตามลำดับในวันถัดไป",
      "每晚选出明天最重要的六件事，并按顺序完成。",
      "毎晩、翌日の重要な仕事を 6 つ選び、順番に片づけます。",
      "매일 저녁 가장 중요한 일 여섯 가지를 골라 다음 날 순서대로 해요.",
    ),
    nodes: [
      node(l("Task 1", "งานที่ 1", "任务 1", "タスク 1", "할 일 1"), RED),
      node(l("Task 2", "งานที่ 2", "任务 2", "タスク 2", "할 일 2"), ORANGE),
      node(l("Task 3", "งานที่ 3", "任务 3", "タスク 3", "할 일 3"), YELLOW),
      node(l("Task 4", "งานที่ 4", "任务 4", "タスク 4", "할 일 4"), GREEN),
      node(l("Task 5", "งานที่ 5", "任务 5", "タスク 5", "할 일 5"), BLUE),
      node(l("Task 6", "งานที่ 6", "任务 6", "タスク 6", "할 일 6"), VIOLET),
      node(word.planTomorrow, TEAL),
    ],
  },
  {
    id: "one-three-five",
    category: "technique",
    name: l("1-3-5 rule", "กฎ 1-3-5", "1-3-5 法则", "1-3-5 ルール", "1-3-5 규칙"),
    description: l(
      "Each day: one big task, three medium ones and five small ones.",
      "ในแต่ละวัน: งานใหญ่หนึ่งอย่าง งานกลางสามอย่าง และงานเล็กห้าอย่าง",
      "每天：一件大事、三件中事、五件小事。",
      "1 日につき、大きな仕事 1 つ、中くらい 3 つ、小さな仕事 5 つ。",
      "하루에 큰 일 하나, 중간 일 셋, 작은 일 다섯.",
    ),
    nodes: [
      node(l("The big task", "งานใหญ่", "大任务", "大きな仕事", "큰 일"), RED),
      node(l("Medium tasks", "งานขนาดกลาง", "中等任务", "中くらいの仕事", "중간 일"), ORANGE),
      node(l("Small tasks", "งานเล็ก", "小任务", "小さな仕事", "작은 일"), BLUE),
      node(word.breaks, GREEN),
    ],
  },
  {
    id: "weekly-planning",
    category: "technique",
    name: l("Weekly planning", "การวางแผนรายสัปดาห์", "每周规划", "週間プランニング", "주간 계획"),
    description: l(
      "A weekly rhythm: review last week, plan the next, and keep a daily check.",
      "จังหวะรายสัปดาห์: ทบทวนสัปดาห์ที่ผ่านมา วางแผนสัปดาห์หน้า และเช็กทุกวัน",
      "每周节奏：回顾上周、规划下周，并每天检查。",
      "週のリズム：先週を振り返り、来週を計画し、毎日確認します。",
      "주간 리듬: 지난주를 돌아보고 다음 주를 계획하고 매일 점검해요.",
    ),
    nodes: [
      node(l("Weekly review", "ทบทวนประจำสัปดาห์", "每周回顾", "週次レビュー", "주간 리뷰"), GREEN, [
        node(l("Look back", "ทบทวนย้อนหลัง", "回顾上周", "振り返り", "돌아보기")),
        node(l("Clear inboxes", "เคลียร์กล่องข้อความ", "清理收件箱", "受信箱の整理", "받은 편지함 정리")),
      ]),
      node(l("Plan the week", "วางแผนสัปดาห์", "规划本周", "今週の計画", "이번 주 계획"), BLUE, [
        node(l("Set goals", "ตั้งเป้าหมาย", "设定目标", "目標設定", "목표 정하기")),
        node(l("Schedule key tasks", "จัดตารางงานหลัก", "安排关键任务", "重要タスクの予定", "핵심 일정 잡기")),
      ]),
      node(l("Daily plan", "วางแผนรายวัน", "每日计划", "1 日の計画", "하루 계획"), YELLOW),
      node(l("Reflection", "ทบทวนความคิด", "反思", "内省", "성찰"), VIOLET),
    ],
  },
  {
    id: "agile-sprint",
    category: "technique",
    name: l("Agile sprint", "สปรินต์แบบอไจล์", "敏捷迭代", "アジャイルスプリント", "애자일 스프린트"),
    description: l(
      "A two-week rhythm: plan, build, show, and look back.",
      "จังหวะสองสัปดาห์: วางแผน สร้าง นำเสนอ และมองย้อนกลับ",
      "两周节奏：规划、开发、演示、复盘。",
      "2 週間のリズム：計画、開発、デモ、振り返り。",
      "2주 리듬: 계획하고, 만들고, 보여 주고, 돌아봐요.",
    ),
    nodes: [
      node(l("Sprint planning", "วางแผนสปรินต์", "迭代规划", "スプリント計画", "스프린트 계획"), BLUE),
      node(word.build, VIOLET),
      node(l("Daily stand-up", "ประชุมยืนประจำวัน", "每日站会", "デイリースクラム", "데일리 스탠드업"), ORANGE),
      node(l("Review and demo", "รีวิวและเดโม", "评审与演示", "レビューとデモ", "리뷰와 데모"), GREEN),
      node(l("Retrospective", "ย้อนมองการทำงาน", "复盘会", "ふりかえり", "회고"), YELLOW),
      node(l("Backlog refinement", "จัดระเบียบแบ็กล็อก", "需求梳理", "バックログ整理", "백로그 정리"), GRAY),
    ],
  },
  {
    id: "monk-mode",
    category: "technique",
    name: l("Monk mode", "โหมดนักบวช", "僧侣模式", "モンクモード", "몽크 모드"),
    description: l(
      "A stretch of intense focus with training, learning and recovery, and little else.",
      "ช่วงโฟกัสเข้มข้น พร้อมการฝึกฝน เรียนรู้ และฟื้นตัว โดยตัดสิ่งอื่นออก",
      "一段高强度专注期：训练、学习、恢复，其他一律从简。",
      "トレーニング、学び、回復だけに絞った集中期間です。",
      "운동, 배움, 회복에 집중하고 나머지는 줄이는 집중 기간이에요.",
    ),
    nodes: [
      node(word.deepWork, VIOLET),
      node(l("Physical training", "ออกกำลังกายจริงจัง", "体能训练", "トレーニング", "체력 훈련"), RED),
      node(word.learning, BLUE),
      node(word.recovery, GREEN, [node(word.sleep), node(word.meals)]),
      node(l("Limited social time", "เวลาสังคมจำกัด", "限制社交时间", "人付き合いは控えめに", "제한된 사교 시간"), GRAY),
    ],
  },
  {
    id: "time-audit",
    category: "technique",
    name: l("Time audit", "ตรวจสอบเวลา", "时间审计", "タイムオーディット", "시간 감사"),
    description: l(
      "Record where your time really goes for a week, then decide what to change.",
      "บันทึกว่าเวลาไปอยู่ที่ไหนจริง ๆ หนึ่งสัปดาห์ แล้วตัดสินใจว่าจะเปลี่ยนอะไร",
      "记录一周时间的真实去向，再决定要改变什么。",
      "1 週間、時間の本当の使い道を記録して、何を変えるか決めます。",
      "일주일 동안 시간이 실제로 어디에 쓰이는지 기록하고 무엇을 바꿀지 정해요.",
    ),
    nodes: [
      node(word.work, BLUE),
      node(word.commute, TEAL),
      node(word.chores, ORANGE),
      node(l("Screen time", "เวลาหน้าจอ", "屏幕时间", "スクリーンタイム", "스크린 타임"), PINK, [
        node(word.socialMedia),
        node(l("Videos and shows", "คลิปและซีรีส์", "视频与剧集", "動画と番組", "영상과 프로그램")),
      ]),
      node(word.sleep, VIOLET),
      node(l("Social time", "เวลาสังสรรค์", "社交时间", "人と過ごす時間", "사교 시간"), YELLOW),
      node(word.learning, GREEN),
      node(l("Unplanned or lost time", "เวลาที่ไม่ได้วางแผนหรือหายไป", "计划外或流失的时间", "予定外・失われた時間", "계획 밖·사라진 시간"), GRAY),
    ],
  },
];
